apiVersion: v1
kind: Service
metadata:
  name: mmessenger-backend
  namespace: messenger
  labels:
    app: mmessenger
    component: backend
spec:
  type: ClusterIP
  selector:
    app: mmessenger
    component: backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
