apiVersion: v1
kind: Service
metadata:
  name: mmessenger-frontend
  namespace: messenger
  labels:
    app: mmessenger
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: mmessenger
    component: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
